server:
  port: 8080

spring:
  # Database (MySQL) Configs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pear?serverTimezone=GMT
    username: root
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB

  # Spring Security Default ID & Password
#  security:
#    user:
#      name: admin
#      password: admin

# Path to where files will be saved
file:
  path: "~/Desktop/uploadedFiles"

